# Generated by Django 4.2.3 on 2023-07-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facevector',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
